[[targets]]
name = "engine"
type = "static_library"
configs = [
  "../build/common.toml:common",
]
deps = [
  "../vectormath/build.toml:vectormath",
]
include_dirs = [
  "include",
  "../vectormath/include",
]
headers = [
  "include/engine/engine.h",
]
sources = [
  "src/engine.cpp",
]

[targets.tagged."windows"]
defines = [
  "_WIN32_WINNT=0x0602", # Windows 8 or later
  "WIN32_LEAN_AND_MEAN",
  "NOMINMAX",
]
headers = [
  "include/engine/TimeSourceWindows.h",
]
sources = [
  "src/TimeSourceWindows.cpp",
]

[targets.tagged."apple"]
defines = [
]
headers = [
  "include/engine/TimeSourceApple.h",
]
sources = [
  "src/TimeSourceApple.cpp",
]

[targets.tagged."linux"]
defines = [
]
headers = [
  "include/engine/TimeSourceLinux.h",
]
sources = [
  "src/TimeSourceLinux.cpp",
]

[targets.tagged."debug"]
defines = [
  "IS_RELEASE_BUILD=0",
]

[targets.tagged."release"]
defines = [
  "IS_RELEASE_BUILD=1",
]
