import = [
  "../vectormath/build.toml",
]

[[executable]]
name = "engine"
include_dirs = [
  "include",
  "../vectormath/include",
]
headers = [
  "include/engine.h",
]
sources = [
  "src/engine.cpp",
]
