import = [
  "../vectormath/build.toml",
]

[[static_library]]
name = "engine"
deps = [
  "vectormath",
]
include_dirs = [
  "include",
  "../vectormath/include",
]
headers = [
  "include/engine.h",
]
sources = [
  "src/engine.cpp",
]
