[[targets]]
name = "vectormath"
type = "static_library"
configs = [
  "../build/common.toml:common",
]
include_dirs = [
  "include",
]
headers = [
  "include/vectormath/Vector2.h",
]
sources = [
  "src/Vector2.cpp",
]
