[[targets]]
name = "vectormath"
type = "static_library"
configs = [
  "../build/common.toml:common",
]
include_dirs = [
  "include",
]
headers = [
  "include/vectormath/Vector2.h",
]
sources = [
  "src/Vector2.cpp",
]

[[targets]]
name = "vectormath_test"
type = "executable"
configs = [
  "../build/common.toml:common",
]
deps = [
  ":vectormath",
]
include_dirs = [
  "include",
]
headers = [
  "test/Vector2Test.h",
]
sources = [
  "test/main.cpp",
  "test/Vector2Test.cpp",
]
