[[targets]]
name = "libpng"
type = "static_library"
deps = [
  "../zlib/build.toml:zlib",
]
include_dirs = [
  "libpng",
  "vendor",
  "../zlib",
]
headers = [
  "vendor/pnglibconf.h",
  "libpng/png.h",
  "libpng/pngconf.h",
  "libpng/pngdebug.h",
  "libpng/pnginfo.h",
  "libpng/pngpriv.h",
  "libpng/pngstruct.h",
]
sources = [
  "libpng/png.c",
  "libpng/pngerror.c",
  "libpng/pngget.c",
  "libpng/pngmem.c",
  "libpng/pngpread.c",
  "libpng/pngread.c",
  "libpng/pngrio.c",
  "libpng/pngrtran.c",
  "libpng/pngrutil.c",
  "libpng/pngset.c",
  "libpng/pngtrans.c",
  "libpng/pngwio.c",
  "libpng/pngwrite.c",
  "libpng/pngwtran.c",
  "libpng/pngwutil.c",
]
