[[targets]]
name = "zlib"
type = "static_library"
include_dirs = [
  "zlib",
]
headers = [
  "zlib/crc32.h",
  "zlib/deflate.h",
  "zlib/gzguts.h",
  "zlib/inffast.h",
  "zlib/inffixed.h",
  "zlib/inflate.h",
  "zlib/inftrees.h",
  "zlib/trees.h",
  "zlib/zconf.h",
  "zlib/zlib.h",
  "zlib/zutil.h",
]
sources = [
  "zlib/adler32.c",
  "zlib/compress.c",
  "zlib/crc32.c",
  "zlib/deflate.c",
  "zlib/gzclose.c",
  "zlib/gzlib.c",
  "zlib/gzread.c",
  "zlib/gzwrite.c",
  "zlib/infback.c",
  "zlib/inffast.c",
  "zlib/inflate.c",
  "zlib/inftrees.c",
  "zlib/trees.c",
  "zlib/uncompr.c",
  "zlib/zutil.c",
]
