[[targets]]
name = "app"
type = "executable"
configs = [
  "../build/common.toml:common",
]
deps = [
  "../engine/build.toml:engine",
]
defines = [
  "USE_MATH=1",
]
include_dirs = [
  "include",
  "../engine/include",
  "../vectormath/include",
]
headers = [
  "include/app/Game.h",
]
sources = [
  "src/Game.cpp",
  "src/main.cpp",
]
