import = [
  "../engine/build.toml",
  "../vectormath/build.toml",
  "../build/common.toml",
]

[[targets]]
name = "app"
type = "executable"
configs = [
  "common",
]
deps = [
  "engine",
]
defines = [
  "USE_MATH=1",
]
include_dirs = [
  "include",
  "../engine/include",
  "../vectormath/include",
]
headers = [
  "include/app/Game.h",
]
sources = [
  "src/Game.cpp",
  "src/main.cpp",
]

[targets.msbuild_settings.ClCompile]
WarningLevel = "Level3"
PrecompiledHeader = "NotUsing"

[targets.tagged."debug".msbuild_settings.ClCompile]
GenerateDebugInformation = "true"

[targets.tagged."release".msbuild_settings.ClCompile]
FunctionLevelLinking = "true"

[targets.tagged."debug".msbuild_settings.Configuration]
UseDebugLibraries = "true"

[targets.tagged."release".msbuild_settings.Configuration]
UseDebugLibraries = "false"

[targets.tagged."windows".msbuild_settings.User]
DebuggerFlavor = "WindowsLocalDebugger"
