import = [
  "../engine/build.toml",
  "../vectormath/build.toml",
  "../build/common.toml",
]

[[targets]]
name = "app"
type = "executable"
configs = [
  "common",
]
deps = [
  "engine",
]
defines = [
  "USE_MATH=1",
]
include_dirs = [
  "include",
  "../engine/include",
  "../vectormath/include",
]
headers = [
  "include/app/Game.h",
]
sources = [
  "src/Game.cpp",
  "src/main.cpp",
]

[targets.msbuild_settings.ClCompile]
WarningLevel = "Level3"
PrecompiledHeader = ""

[targets.msbuild_settings.Link]
SubSystem = "Console"
GenerateDebugInformation = "true"

[targets.tagged."debug".msbuild_settings.ClCompile]
Optimization = "Disabled"
SDLCheck = "true"

[targets.tagged."release".msbuild_settings.Link]
EnableCOMDATFolding = "true"
OptimizeReferences = "true"

[targets.tagged."release".msbuild_settings.ClCompile]
FunctionLevelLinking = "true"
Optimization = "MaxSpeed"
IntrinsicFunctions = "true"

[targets.msbuild_settings.Configuration]
ConfigurationType = "Application"
PlatformToolset = "v140"
CharacterSet = "Unicode"

[targets.tagged."debug".msbuild_settings.Configuration]
UseDebugLibraries = "true"

[targets.tagged."release".msbuild_settings.Configuration]
UseDebugLibraries = "false"
WholeProgramOptimization = "true"

[targets.tagged."windows".msbuild_settings.User]
DebuggerFlavor = "WindowsLocalDebugger"

[targets.tagged."debug".msbuild_settings.General]
LinkIncremental = "true"

[targets.tagged."release".msbuild_settings.General]
LinkIncremental = "false"
